### ISSUE TITLE
Am I missing something. What does it actually do?

### ISSUE THREAD

**Issue by kingsofcoms** [tympanix/subsync#1]
(my36) root@ubuntu:~# subsync /root/sample.mkv
    Transcoding...
    Analysing...
    Predicting values...
    Fitting...
    Shift 0.032 seconds:

Entire subtitle got shifted by .032s, i thought this app would either generate a subtitle from speech detection or if .srt is provided it would re-adjust and align sentences perfectly with begin and end of voice.

**Comment by tympanix** [comment]
It shifts the entire subtitle to match the audio. It does not adjust the every subtitle individually. It uses speech detection to find *where* the speech is, not speech recognition. That would produce horrible results I think.

Maybe you could consider every subtitle individually in the future.

**Comment by kingsofcoms** [comment]
you linked https://machinelearnings.co/automatic-subtitle-synchronization-e188a9275617 so i thought this would sync every sentence/word of subtitle.

**Comment by tympanix** [comment]
The program does exactly what is described in the article. And it does not sync every sentence. Just the subtitle as a whole.
