### ISSUE TITLE
Not able to install in Ubuntu 19.10/ Python 3.7

### ISSUE THREAD

**Issue by davidgar8** [tympanix/subsync#21]
Hi,

I'm not able to install subsync due to following error:
```
$ pip3 install subsync
...
ERROR: Could not find a version that satisfies the requirement tensorflow==1.5.1 (from subsync) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0)
ERROR: No matching distribution found for tensorflow==1.5.1 (from subsync)
```

Seems to me that tensorflow 1.5.1 is not available for python 3.7 (just 1.13 onwards).

This issue is slightly different to this one, as in that case it seem like a network issue or something and there was no version at all.
https://github.com/tympanix/subsync/issues/9

Thanks!

**Comment by tympanix** [comment]
I think you should try to force install another version of tensorflow. The versions listed above should be those compatible with your system. Although subsync was tested and implemented with tensorflow 1.5.1, I think other versions of tensorflow should work. Maybe the hardcoded tensorflow version should be removed from `requirements.txt`?

Sorry for late reply
