### ISSUE TITLE
Add Information About Command-Line Usage In Readme

### ISSUE THREAD

**Issue by bereddy** [tympanix/subsync#25]
Thanks for all the work that was done to develop this great tool.

I think it might be useful to include a few lines in the Readme file with information about how to use subsync from the command line after installing it with PIP.

I suggest this in part because I've had no luck so far getting subsync to run from the command line with a simple test .mp4 file accompanied by a .srt that I'd like to resynchronize with subsync.

I fully admit that I have next to no Python experience, which is making it very difficult to figure out how to use the program from the command line.

I try as best I can, but all I can get is error messages like this:

```
$ sudo /home/tuser/.local/bin/subsync temp.mp4 temp.srt
/home/tuser/.local/lib/python2.7/site-packages/librosa/__init__.py:35: FutureWarning: You are using librosa with Python 2. Please note that librosa 0.7 will be the last version to support Python 2, after which it will require Python 3 or later.
  FutureWarning)
Traceback (most recent call last):
  File "/home/tuser/.local/bin/subsync", line 4, in <module>
    subsync.run()
  File "/home/tuser/.local/lib/python2.7/site-packages/subsync/main.py", line 32, in run
    from .media import Media
  File "/home/tuser/.local/lib/python2.7/site-packages/subsync/media.py", line 17, in <module>
    from .ffmpeg import Transcode
  File "/home/tuser/.local/lib/python2.7/site-packages/subsync/ffmpeg.py", line 9, in <module>
    from subprocess import DEVNULL, STDOUT, PIPE
ImportError: cannot import name DEVNULL
```

**Comment by tympanix** [comment]
I have included the output of `subsync --help` in the readme - I apologise if it is hard to understand. You are calling the program correctly, although `subsync temp.srt` should be enough, it will find the video automatically.

I think you should try python3 to fix the error
