### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by riku2015** [tympanix/subsync#6]
Heya, tried to run, installed pip pip2 and pip3
ubuntu18 64bit
.........................................................
python3.6 /home/riku/.local/bin/subsync 'moviename.mp4'
Illegal instruction (core dumped)
.........................................................
python /home/riku/.local/bin/subsync 'moviename.mp4'
Traceback (most recent call last):
  File "/home/riku/.local/bin/subsync", line 4, in <module>
    subsync.run()
  File "/home/riku/.local/lib/python2.7/site-packages/subsync/main.py", line 32, in run
    from .media import Media
  File "/home/riku/.local/lib/python2.7/site-packages/subsync/media.py", line 16, in <module>
    from .ffmpeg import Transcode
  File "/home/riku/.local/lib/python2.7/site-packages/subsync/ffmpeg.py", line 9, in <module>
    from subprocess import DEVNULL, STDOUT, PIPE
ImportError: cannot import name DEVNULL

im not sure what is happening here.. other is python3 and other is 2. there is no info what python version should use so i tried both.

**Comment by tympanix** [comment]
Python 3 should be your best option. As you can see you did not invoke python3 correctly as you are still using python2.7 in the logs. Have you tried with `python3.6 -m subsync moviename.mp4`?

**Comment by riku2015** [comment]
yes.

_**python3.6**_ /home/riku/.local/bin/subsync 'moviename.mp4'
Illegal instruction (core dumped)

**Comment by riku2015** [comment]
yes

**python3.6** /home/riku/.local/bin/subsync 'moviename.mp4'
Illegal instruction (core dumped)

$ python3.6 -m subsync 'file.mp4'             
Illegal instruction (core dumped)

**Comment by tympanix** [comment]
Okay so the problems seems to be that your CPU does not support the version of tensorflow that subsync is using. I myself had to downgrade tensorflow to v1.5.1 - and in fact that is what subsync is using. You may try to clone the project, create a virtual python environment and test with different versions of tensorflow. You can read additional information here https://github.com/tensorflow/tensorflow/issues/17411. Subsync is very experimental at this stage and I am afraid I am only able to give you limited support concerning this issue.

**Comment by riku2015** [comment]
Okey this is resolved :) fixed by doing this. version 1.5.1 wont work, it need to be 1.5
**pip3 uninstall tensorflow
pip3 install tensorflow==1.5**

Now i can start playing around... first impression is need to re-encode all subtitle files to utf8. its not problem iconv can do it. :) 
for now i havent got it working yet, but keep trying different options. and hope i get some sync! very promising software

**Comment by tympanix** [comment]
Glad you got it working. In my experience subtitles are synced correctly ~75% percent of the time - so definitely some opportunity for improvement. See how well it works for you!

**Comment by riku2015** [comment]
tried one movie and the subtitles are badly offset, it cannot repair it, tried alot settings increased alot duration and margins. anyways it was badly offset  so no wonder it was not able do it :D
Also tried a serie it however managed to ajust about in the middle of it, but end  was offset. 

Maybe implement at some point 2-point sync, like timeajuster.  then it should work when sync on start and at the end. 
Already love this :) this saves alot time not manually ajust subtitles

**Comment by tympanix** [comment]
Actually that is already implemented with the `-r` flag. It will recursively sync every sentence in the subtitle. For my limited testing it works quite well.

**Comment by riku2015** [comment]
okey now you said it, i started to experiment more with it, it actually works very well when subtitles are going offset torwards end.
automated whole season of certain serie where have that problem, it fixed all 13 episodes seamlessly :DD this is looking very good when you have this small out of sync issues... it saves *ALOT* of time...
Combineing this with opensubtitles automatic downloader.. on scripts.
