### ISSUE TITLE
No matching distribution found for tensorflow

### ISSUE THREAD

**Issue by RahManJunior** [tympanix/subsync#9]
Hello, I'm extremely noob regarding python but I really want to use this
When doing pip install subsync I get this error:
Collecting subsync
  Using cached https://files.pythonhosted.org/packages/9c/6a/ebdc4e6a54cc7c9c80284ec1bbf3333ec8f7cc817a05cb9ff5c28055fb2f/subsync-0.1.5.tar.gz
Collecting tensorflow==1.5.1 (from subsync)
  Could not find a version that satisfies the requirement tensorflow==1.5.1 (from subsync) (from versions: )
No matching distribution found for tensorflow==1.5.1 (from subsync)

**Comment by tympanix** [comment]
Finding a compatible package version of tensorflow is the most common problem. The tool has been developed with v1.5.1 which is what is being downloaded. It seems there is no tensorflow package for your machine (what architecture is your pc?). I would suggest trying out and installing different versions of tensorflow with `pip` until you find one which is compatible with your system. Then you can clone and change to that tensorflow version for subsync.

Maybe this can help you as well https://www.tensorflow.org/install/pip.

**Comment by Suleman-Elahi** [comment]
![image](https://user-images.githubusercontent.com/24384996/53402813-6e6f0700-39d8-11e9-8902-7ea410ab76e9.png)

Problems on Windows 10

**Comment by tympanix** [comment]
Have you, as described above, tried other version of tensorflow?

**Comment by Suleman-Elahi** [comment]
Well I think it is a temporary problem The main package mentioned on the official websites of `tensorflow` is not working either for Windows.
![image](https://user-images.githubusercontent.com/24384996/53541570-79dd4200-3b40-11e9-9782-c8e2c9024d48.png)

**Comment by tympanix** [comment]
Yes this seems like a problem with tensorflow and not subsync. Make sure you can install tensorflow first, before you try installing subsync.

N.B. I am aware that tensorflow can be a bit tedious and I have been considering using PyTorch or even an already implemented VAD such as the one in webRTC.
